steps:

# Build, tag and push snowcover image to Container Registry
# Uses Kaniko for caching layers (6h ttl) 
# Warning this may prevent picking changes to requirements.txt
- name: 'gcr.io/kaniko-project/executor:latest'
  args: 
  - --destination=europe-west6-docker.pkg.dev/$PROJECT_ID/ohd-repo/ohdataweb:$SHORT_SHA
  - --cache=true
  - --cache-ttl=6h

timeout: 1500s